title: Finite Adventures
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://finiteadventures.com" # the base hostname & protocol for your site

# Build settings
environment: production
source: ./src
